contract_name = "BundleEncoder"

[structs.Bundle]
type = "tuple(string a, string[] b, uint64 c)"

[functions.encode]
inputs = ["Bundle"]
template = '''
{
   "other": [ {{range .obj0.b}} {{toString .}} {{end}}],
   "other2": "a b",
   "number": {{toString .obj0.c}}
}
'''

[functions.decode]
output = "Bundle"
template = '''
{
   "number": {{.obj0.number}}
}
'''