// SPDX-License-Identifier: UNLICENSED
// DO NOT edit this file. Code generated by template-json.
pragma solidity ^0.8.8;

import "solady/src/utils/LibString.sol";

library BundleEncoder {
    struct Bundle {
        string a;
        string[] b;
        uint64 c;
    }

    function encode(Bundle memory obj0) internal pure returns (bytes memory) {
        bytes memory body;
        body = abi.encodePacked(body, '{   "other": [');
        for (uint64 i = 0; i < obj0.b.length; i++) {
            body = abi.encodePacked(body, LibString.toString(obj0.b[i]));
            if (i < obj0.b.length - 1) body = abi.encodePacked(body, ",");
        }
        body = abi.encodePacked(body, ']   "number":', LibString.toString(obj0.c), "}");
        return body;
    }
}
