name: Check forge-gen
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check-docs-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Build the contracts
        run: forge build

      - name: Generate forge-docs
        run: cd tools/docs-gen && go run main.go --suave-std ../../
